#---
base:
    core:
        defaultCacheManager:
            fallbackToNoOpCache: false

        defaultMessageSource:
            alwaysUseMessageFormat: true
            fallbackToSystemLocale: true
            useCodeAsDefaultMessage: true

        restTemplate:
            connectionTimeout: 15000
            readTimeout: 30000
            writeTimeout: 30000

        GlobalEventRoutingListener:
            exchange: 163yun-globalEvent-exchange

        threadPoolTaskScheduler:
            poolSize: 3
            removeOnCancelPolicy: false
            daemon: false
            waitForTasksToCompleteOnShutdown: true
            threadPriority: 5
            awaitTerminationSeconds: 5

        SnowflakeIdGenerator:
            hostId: -1
            startEpoch: 1489475366535
